# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'BLKProperty' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

  # Pods for BLKProperty

#Objective-C
pod 'FDFullscreenPopGesture', '~> 1.1'


#Swift
#键盘
#pod 'IQKeyboardManagerSwift', '~> 4.0.7'
#请求
pod 'Alamofire', '~> 4.2.0'
#解析json
pod 'SwiftyJSON', '~> 3.1.3'
#下拉刷新
pod 'NVActivityIndicatorView', '~> 3.0'
#加载图片
pod 'Kingfisher', '~> 3.2.1'
#一个iOS8风格的HUD,效果不错
pod 'PKHUD', '~> 4.0.0'
#加密解密,支持MD5,SHA,HMac,AES等
pod 'CryptoSwift', '~> 0.6.6'


  #target 'BLKPropertyTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

  #target 'BLKPropertyUITests' do
    #inherit! :search_paths
    # Pods for testing
  #end

end
